// <auto-generated />
using System;
using Horth.Service.Email.Scheduler.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Horth.Service.Email.Scheduler.Migrations
{
    [DbContext(typeof(SchedulerServiceDbContext))]
    [Migration("20210604170057_June6-2024")]
    partial class June62024
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Horth.Service.Email.Scheduler.Model.SchedulerResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Job")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastRunEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultJoson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchedulerResult");
                });
#pragma warning restore 612, 618
        }
    }
}
